#!/usr/bin/python
#-*- coding: utf-8 -*-
rdflib as r, pygraphviz as gv


G(U(part),rdf.type,opa.ParticipationPortal)
G(ind,rdf.type,opa.Member)

    G( ind,opa.name, L(Q("name")) )
        G(ind,rdf.type,opa.Participant)
        G( ind,opa.mbox,U("mailto:%s"%(Qu("email"),)) )
        G(ind,rdf.type,opa.Group)
        G(ind,rdf.type,opa.Organization)
    G(ind,opa.visibleProfile, L(Q("visible"),xsd.boolean) )
    G(ind,opa.publicProfile, L(Q("public_profile"),xsd.boolean))
        G(lugar,rdf.type,opa.Point )
        G(ind, opa.based_near, lugar )
        G(lugar,opa.lat, L(Q("lat")))
        G(lugar,opa.long,L(Q("lng")))
    G(ind,opa.created,L(Q("created_at"),xsd.dateTime))
    G(ind,opa.modified,L(Q("updated_at"),xsd.dateTime))
    G(ind,opa.city,L(cid))
            G(ind,opa.country,L(cid))
            G(ind,opa.state,L(cid))
            G(ind,opa.professionalActivity,L(cid))
            G(ind,opa.organization,L(cid))
            ART = opa.Article+"#"+str(QA("id"))
            G(ART,opa.publisher,ind)
            G(ART,opa.atype,L(tipo))
                    G(ART,opa.title,L(name))
                    G(ART,opa.atype,opa.ParticipationTrack)
                    G(ART,opa.atype,opa.ParticipationStep)
                    G(ART2,opa.hasStep,ART)
                G(ART,opa.body,L(remove_tags(body)) )
                G( ART,opa.abstract,L(remove_tags(abst)) )
            G(ART,opa.created,L( QA("created_at"),xsd.dateTime))
            G(ART,opa.modified,L(QA("updated_at"),xsd.dateTime))
        COM=opa.Comment+"#"+str(QC("id"))
        G(COM,rdf.type,opa.Comment)
        G(COM,opa.creator,ind)
            G(COM,opa.title,L(QC("title")))
        G(COM,opa.body,L(remove_tags(QC("body"))))
        G(COM,opa.created,L(QC("created_at"),xsd.dateTime))
                ART = opa.Article+"#"+str(QC("source_id")) # VERIFICAR
                G(ART,opa.hasReply,COM)
                turi=opa.Comment+"#"+rip
                G(turi , opa.hasReply , COM )
            G(COM,opa.ip,L(QC("ip_address")))
        g.add((ind1,opa.knows,ind2))
        tfr=opa.Friendship+"#"+("%s-%s"%tuple(am))
        G(tfr,opa.member,ind1)
    tfr=opa.Vote+"#"+str(voto[0])
    G(tfr,rdf.type,opa.Vote)
    G(tfr,opa.voter,ind)
